// src/js/react/buttons.component.jsx
import React from 'react'
import { decrement, increment } from 'reduxstore/action/index'

export default () =>
  <div className='btn-group'>
    <button className='btn btn-default btn-lg' onClick={increment}>+</button>
    <button className='btn btn-default btn-lg' onClick={decrement}>-</button>
  </div>

// src/js/angular2/buttons.component.ts
import { Component } from '@angular/core';
import { decrement, increment } from 'reduxstore/action/index';

@Component({
  selector: 'buttons',
  template: `
    <div class="btn-group">
      <button (click)="increment($event)" class="btn btn-default btn-lg">+</button>
      <button (click)="decrement($event)" class="btn btn-default btn-lg">-</button>
    </div>
  `
})

export class ButtonsComponent {
  increment ($event) {
    increment();
  }

  decrement ($event) {
    decrement();
  }
}
